name: tests

on:
  push:
  pull_request:

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ["8.2"]
        shopware: ["6.7.*"]

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2

      - name: Install deps (force Shopware version)
        run: |
          composer require "shopware/core:${{ matrix.shopware }}" --no-update
          composer install --no-interaction --prefer-dist
          composer update shopware/core --with-all-dependencies --no-interaction

      - name: Run tests
        run: vendor/bin/phpunit
